# This file was generated by GoReleaser. DO NOT EDIT.
cask "newsfetch" do
  version "0.7.0"

  on_macos do
    on_arm do
      sha256 "3682a60b7f9128eb22827c812e5ab2380e86a66af3a74014321485400f2a55f5"
      url "https://github.com/PietroCoppola/newsfetch/releases/download/v#{version}/newsfetch_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "448fef0d40369e4f02d144ac178b3559e9896445895681de2d1f9329ea46c0d6"
      url "https://github.com/PietroCoppola/newsfetch/releases/download/v#{version}/newsfetch_#{version}_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "db4bf4cf9231c23bfd036fef1ebdebc509d86afbd1f5020c1813043445c6eadd"
      url "https://github.com/PietroCoppola/newsfetch/releases/download/v#{version}/newsfetch_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7ad2d1d76581d6e07455111bf8b7e3bdf460b30d31139b7be0af138d1e3c8a7b"
      url "https://github.com/PietroCoppola/newsfetch/releases/download/v#{version}/newsfetch_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "newsfetch"
  desc "A small CLI that prints one piece of bite-sized tech news every time you open a terminal."
  homepage "https://github.com/PietroCoppola/newsfetch"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "newsfetch"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/newsfetch"]
    end
  end

  # No zap stanza required
end
