# This file was generated by GoReleaser. DO NOT EDIT.
cask "newsfetch" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "1ccac157e25b2de438217fc063cf4dc9d6e53b6f3a90e6ed16ddf1dd4e0f9769"
      url "https://github.com/PietroCoppola/newsfetch/releases/download/v#{version}/newsfetch_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9db2602122835f5f4b9f2519e49180eecb28ced4e1d05751af9fc023e5691193"
      url "https://github.com/PietroCoppola/newsfetch/releases/download/v#{version}/newsfetch_#{version}_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "20544dc5f99388bb692314d99b006cf4964114b02d08110c8a370bde893b3665"
      url "https://github.com/PietroCoppola/newsfetch/releases/download/v#{version}/newsfetch_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c59b8b7223f7cb6843393dd822d67cd82b191ed06bdd5a8a2d441fe882cb23a1"
      url "https://github.com/PietroCoppola/newsfetch/releases/download/v#{version}/newsfetch_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "newsfetch"
  desc "A small CLI that prints one piece of bite-sized tech news every time you open a terminal."
  homepage "https://github.com/PietroCoppola/newsfetch"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "newsfetch"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/newsfetch"]
    end
  end

  # No zap stanza required
end
