# This file was generated by GoReleaser. DO NOT EDIT.
cask "newsfetch" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "dcc166687964a16daccf9c4ad01da1fb794901e68182fe4d3dfac0189d573b32"
      url "https://github.com/PietroCoppola/newsfetch/releases/download/v#{version}/newsfetch_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ea5756c2626435ecf6312f6af165889b97147d9eef19cab7023c89fedc5ecaf2"
      url "https://github.com/PietroCoppola/newsfetch/releases/download/v#{version}/newsfetch_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ce0992b5da08706cd604cd9fce1cce80c3b8c75f97a3e480a6484de56905fa99"
      url "https://github.com/PietroCoppola/newsfetch/releases/download/v#{version}/newsfetch_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "84681ade1e2b07535037a1416fec60eee9f7e1e973a2fcc457085a139e893bdf"
      url "https://github.com/PietroCoppola/newsfetch/releases/download/v#{version}/newsfetch_#{version}_linux_arm64.tar.gz"
    end
  end

  name "newsfetch"
  desc "A small CLI that prints one piece of bite-sized tech news every time you open a terminal."
  homepage "https://github.com/PietroCoppola/newsfetch"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "newsfetch"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/newsfetch"]
    end
  end

  # No zap stanza required

end
